### Get all users
GET http://localhost:8081/users

### Get a specific user
GET http://localhost:8081/users/john_doe

### Get a specific user - testing for no existing user
GET http://localhost:8081/users/smith_john

### Create a user
POST http://localhost:8081/users
Content-Type: application/json

{
    "firstName": "Johnt",
    "lastName": "Smith",
    "emailAddress": "smithjohn@gmail.com",
    "username": "smith_john",
    "statusText": "I love my life of software development",
    "password": "123456789",
    "profilePhoto": "https://example.com/jane_smith.jpg",
    "coverPhoto": "https://example.com/jane_smith_cover.jpg"
}

### Delete a user
DELETE http://localhost:8081/users/smith_account2

### Get a specific user - testing for no existing user
GET http://localhost:8081/users/smith_john

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "firstName": "Kellen"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "lastName": "Gitahii"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "newEmailAddress": "kellen_@gmail.com"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "statusText": "do what you do best and be happy doing it darling"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "password": "112345678"
}


### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "firstName": "eva"
}

### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "newUsername": "this_is_eve"
}

### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "newEmailAddress": "eve22@gmail.com"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "",
    "password": "123456789"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "eve@gmail.com",
    "password": "12345678"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "eve",
    "password": "12345678"
}

# on update, return the updated user object which will also be used to update state in the frontend


### get all posts
GET http://localhost:8081/posts

### create a post
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doees"
}

### create a post - no image and text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "image": "https://example.com/image.png"
}

### another post
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "image": "https://example.com/image.png",
    "text": "am getting married next week, I just wanted to tell you this is her"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "text": "I am going to miami next week, whose coming"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "text": "I am going to miami next week, whose coming",
    "image": "https://example.com/image.png"
}

### get a single post
GET http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5

### update a post
PATCH http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5
Content-Type: application/json

{
    "username": "john_doe",
    "text": "am getting married next week, I just wanted to tell you this is her, and I really love her"
}

### update a post
PATCH http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5
Content-Type: application/json

{
    "username": "john_doe",
    "image": "https://example.com/image-new.png"
}

### DELETE A POST
DELETE http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5
Content-Type: application/json

{
    "username": "john_doe"
}