### Get all users
GET http://localhost:8081/users

### Get a specific user
GET http://localhost:8081/users/doe

### Get a specific user - testing for no existing user
GET http://localhost:8081/users/smith_john1

### Create a user
POST http://localhost:8081/users
Content-Type: application/json

{
    "firstName": "Johnt1",
    "lastName": "Smith1",
    "emailAddress": "smithjohn1@gmail.com",
    "username": "smith_john1",
    "statusText": "I love my life of software development",
    "password": "123456789",
    "profilePhoto": "https://example.com/jane_smith.jpg",
    "coverPhoto": "https://example.com/jane_smith_cover.jpg"
}

### Delete a user
DELETE http://localhost:8081/users/smith_john1

### Get a specific user - testing for no existing user
GET http://localhost:8081/users/smith_john

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "firstName": "Kellen"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "lastName": "Gitahii"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "newEmailAddress": "kellen_@gmail.com"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "statusText": "do what you do best and be happy doing it darling"
}

### Update user information
PATCH http://localhost:8081/users/kellen
Content-Type: application/json

{
    "password": "112345678"
}


### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "firstName": "eva"
}

### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "newUsername": "this_is_eve"
}

### Update user information
PATCH http://localhost:8081/users/I_am-eve
Content-Type: application/json

{
    "newEmailAddress": "eve22@gmail.com"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "smith_john1",
    "password": "123456789"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "smithjohn1@gmail.com",
    "password": "123456789"
}

### Login user
POST http://localhost:8081/auth/users/login
Content-Type: application/json

{
    "loginEntity": "eve",
    "password": "12345678"
}

# on update, return the updated user object which will also be used to update state in the frontend


### get all posts
GET http://localhost:8081/posts

### create a post
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doees"
}

### create a post - no image and text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "image": "https://example.com/image.png"
}

### another post
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "text": "am getting married next week, I just wanted to tell you this is her, guys, she is just the one everytime I see her I feel like an angel is missing in heaven, she looks like one of them",
    "image": "https://example.com/bride.png"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "text": "I am going to miami next week, whose coming"
}

### create a post - text
POST http://localhost:8081/posts
Content-Type: application/json

{
    "username": "john_doe",
    "text": "I am going to miami next week, whose coming",
    "image": "https://example.com/image.png"
}

### get a single post
GET http://localhost:8081/posts/12298426-9f66-465c-a94b-7c1a7e65bd71

### update a post
PATCH http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5
Content-Type: application/json

{
    "username": "john_doe",
    "text": "am getting married next week, I just wanted to tell you this is her, and I really love her"
}

### update a post
PATCH http://localhost:8081/posts/aa4e43b2-1db4-4cf5-ac58-3a2bbe6136d5
Content-Type: application/json

{
    "username": "john_doe",
    "image": "https://example.com/image-new.png"
}

### get all posts
GET http://localhost:8081/posts

### get a user
GET http://localhost:8081/users/doe

### DELETE A POST
DELETE http://localhost:8081/posts/2b977f3b-2200-4c70-a65c-c07e287d346f
Content-Type: application/json

{
    "username": "doe"
}



# all about comments
# d904a80e-4c16-48a2-a011-b0002a1f1dc1 -> test comments with this link
### create a comment
POST http://localhost:8081/comments/d904a80e-4c16-48a2-a011-b0002a1f1dc1
Content-Type: application/json

{
    "author": "dennis_otwoma",
    "comment_text": "That is very cute of you guys, hoping to get there soon"
}

### create a comment
POST http://localhost:8081/comments/d904a80e-4c16-48a2-a011-b0002a1f1dc1
Content-Type: application/json

{
    "author": "I_am-eve22",
    "comment_text": "Congratulations man, once again, am happy for you"
}

### Get all comments belonging to a post
GET http://localhost:8081/comments/3788d93d-5267-419f-953f-d3df40dc2487

### update a comment
PATCH http://localhost:8081/comments/123CommentId

### delete a comment
DELETE  http://localhost:8081/comments/123CommentId


### get a single post
GET http://localhost:8081/posts/d904a80e-4c16-48a2-a011-b0002a1f1dc1

### The follows relationship

### Create a follow relationship
POST http://localhost:8081/follows/dennis_otwoma/I_am-eve22
# Here, it will mean I_am-eve22 is the logged in user and dennis_otwoma is the user being followed

### Create a follow relationship
POST http://localhost:8081/follows/I_am-eve22/dennis_otwoma



### Create a follow relationship
DELETE http://localhost:8081/follows/I_am-eve22/dennis_otwoma
# in this context, dennis_otwoma is the logged in user unfollowing I_am-eve22

### Delete a follow relationship
DELETE http://localhost:8081/follows/user-id-1/user-id-2

### Get all users not being followed by the current user/all users that the current user is not following
GET http://localhost:8081/follows/not_following/dennis_otwoma